### ISSUE TITLE
Asynchronously load fonts

### ISSUE THREAD

**Issue by chriskrycho** [rust-lang/beta.rust-lang.org#241]
We can get better first-load times by smartly loading the fonts *after* the page loads. As things stand, we have a blocking load for the CSS in the `head`, and *that* triggers its own blocking load by using the `@import` syntax.

- [x] migrate the font loading directly into the page, so that it can at least load in parallel with CSS (#242)
- [ ] use [a progressive font-loading strategy](https://www.filamentgroup.com/lab/font-events.html) using the very small [FontFaceObserver](https://github.com/bramstein/fontfaceobserver) script (this is incredibly easy to set up)

**Comment by yoshuawuyts** [comment]
Now that we're loading fonts directly, using font-face swap, and preload tags, I think we've covered most optimizations. Closing!
