### ISSUE TITLE
Consider using fewer <code> tags

### ISSUE THREAD

**Issue by nrc** [rust-lang/beta.rust-lang.org#366]
Since the code style involves a box, overuse of code tags makes prose text quite noisey. I suggest that we only use code tags for actual code and text that is entered on the command line. We should not use it for the names of tools (e.g., Cargo, Rustup) or for the names of crates (e.g., ferris-says) or for the names of files and directories (e.g., Cargo.toml, hello-rust).

For example, we would write

To test that you have Rust and Cargo installed, you can run this in your terminal of choice: `cargo --version`

Rather than

To test that you have Rust and `cargo` installed, you can run this in your terminal of choice: `cargo --version`

(note the consistency between 'Rust' and 'Cargo').

**Comment by nicoburns** [comment]
Perhaps the [&lt;dfn&gt;](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dfn), or even the [&lt;abbr&gt;](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr) tag could be used instead for these instances. This would allow us to continue to differentiate them visual, or even add tooltips explaining what they are if we wanted to.

**Comment by chriskrycho** [comment]
In my view both of those suggested tags are semantically inappropriate for what we're doing there, especially `abbr` – we could use `dfn` but only if we supplied a definition. I think we'd be better of just not styling them at all.
