### ISSUE TITLE
ensure data for teams is correct

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-lang/beta.rust-lang.org#378]
- [x] community team - @ashleygwilliams 
- [x] compiler/languages team - @nikomatsakis 
- [x] devtools team - @nrc 
- [x] documentation team - @steveklabnik 
- [x] library team - @alexcrichton 
- [ ] operations team - @Mark-Simulacrum @aidanhs 
- [x] moderation team - @Manishearth 
- [x] alumni - @aturon 
- [x] core team - @ashleygwilliams

**Comment by Mark-Simulacrum** [comment]
Having merged https://github.com/rust-lang/beta.rust-lang.org/pull/406 I believe release team membership is as up to date as it can be -- membership is not very strict currently -- so I'm closing this.
