### ISSUE TITLE
Could Ferris run at the bottom of the window?

### ISSUE THREAD

**Issue by P-E-Meunier** [rust-lang/beta.rust-lang.org#399]
# Design Feature Request
## Summary
A little Ferris running back and forth (not for too long, obviously) at the bottom of the window would be pretty nice.

## Motivation
In pages like "Getting Started", I'm likely to go back and forth between my browser and my terminal, and to miss the cute little crab.

## Drawbacks
If it runs for too long, it's gonna be annoying to readers.

**Comment by ashleygwilliams** [comment]
i agree that the crab is quite cute- but i can imagine that a ferris running at the bottom of the window could be distracting for folks. perhaps we could add it as an easter egg once critical work on the site has slowed down! let's think about something like this at the beginning of next year :)
