### ISSUE TITLE
consider a less bright yellow for highlight

### ISSUE THREAD

**Issue by binomial0** [rust-lang/beta.rust-lang.org#408]
Some subheadings, are difficult to read because of sharp contrasts in the background.

![why_rust_original](https://user-images.githubusercontent.com/7315000/49244073-37a44780-f40f-11e8-9316-3dbb37604d66.png)

To me, the effect looks most jarring with the first subheading ("Why Rust?"), presumably because the contrast between the teal background and the purple rectangle is quite prominent. It's much less prominent at "Build it in Rust", and when it comes to the third subheading, "Rust in Production", I don't see this problem. (That's not surprising - the background is yellow on white, which is a much weaker contrast).

I think the problem is due to the combination of high background-to-background contrast, not that high foreground-to-background contrast, and the fact that a high-contrast edge lies directly behind the text. Each of these elements makes sense in the context of the overall design, so I'm sure this problem will involve some tradeoffs.

I know this issue is pretty subjective, so if you disagree or agree that this looks mildly irritating, please comment below.

**Comment by binomial0** [comment]
I have an Idea in which direction a fix might go, but I'm not sure if it actually looks better.
![why_rust_changed](https://user-images.githubusercontent.com/7315000/49244345-df217a00-f40f-11e8-8b7b-404fb4577a35.png)
This gets rid of the described issue (the text is more easily readable now), but it also lacks some solid, "blocky" feeling that the original (and the design of the whole site) has.  
(CSS changes: `.highlight { height: 20px; top: -18px; /* rest unchanged */ }` in app.css)

**Comment by rep-nop** [comment]
Definitely agree, I think "cartoonish" is a good way to describe it. Super hard to read some of the titles and a lot of the colors & color combinations don't look particularly great. Font is also way too thick in my opinion and makes the characters kind of bleed into each other, which doesn't help.

**Comment by ashleygwilliams** [comment]
i think we'll start by addressing this with the suggestion in #432 - once a patch for that lands, if you still feel the issue hasn't been addressed you can reopen this or file a new one. thanks for filing!

**Comment by jonas-schievink** [comment]
@ashleygwilliams #432 does not address the contrast issue, which is definitely still there. I've found that this heading is one of the worst offenders in that regard:

![screenshot-2018-11-29-21 58 18](https://user-images.githubusercontent.com/1786438/49252926-a096ba00-f425-11e8-8542-db31f1721a57.png)

(this is after the letter spacing fix)
Replacing the yellow with something that's less aggressive on the eyes could work here.

OTOH my biggest problem with the "Why Rust?" header is that the text is completely white, and white-on-dark text generally isn't very readable. Perhaps using a slightly darker text color could help here?

**Comment by ashleygwilliams** [comment]
repoening and renaming to address @jonas-schievink's last comment. thanks for making the ask more specific ! it's helpful.

i would encourage folks on this thread to not use this to pile on, so please keep the comments actionable and constructive (many have been straying from that on this particular thread). i don't want good feedback to be lost in a sea of noise. thank's ya'll!

**Comment by ashleygwilliams** [comment]
@jonas-schievink if you would like to make a PR with a different yellow color suggestion i would be very open to that! (please provide screencaps in the PR) thank you!

**Comment by ashleygwilliams** [comment]
this was closed by #542
