### ISSUE TITLE
wording tweak suggestions for the "Why Rust?" section

### ISSUE THREAD

**Issue by oconnor663** [rust-lang/beta.rust-lang.org#409]
These suggestions are from the perspective of someone who's reasonably familiar with compilers, so it's possible that they're the wrong choice for marketing to (say) web developers. Anyway, with that said:

---

> Rust is blazingly fast and memory-efficient: with no runtime or garbage collector, it can power performance-critical services, run on embedded devices, or **even** integrate with other languages.

A minor nitpick about "even". Integrating with other languages per se isn't that impressive. Essentially all mainstream languages can call code in at least C. The big difference is that Rust can do it with low or no performance overhead. Maybe something like this could capture it:

> Rust is blazingly fast and memory-efficient: with no runtime or garbage collector, it can power performance-critical services, run on embedded devices, or integrate with operating system kernels.

---

> Rust's rich type system and **rock-solid compiler** guarantee memory-safety and thread-safety — and enable you to eliminate many other classes of bugs at compile-time.

This line sort of implies that the reason C and C++ can't guarantee memory safety, is that those compilers "aren't rock solid," which of course isn't what the author meant. There are also arguably some soundness holes in the current Rust compiler that might make some people question its rock solidity, even if those are just academic examples that won't ever come up in production.

Maybe we could replace "rock solid compiler" with "borrow checker", or maybe just drop it.

**Comment by oconnor663** [comment]
I should emphasize that these are of course really specific nitpicks that only a tiny sliver of programmers will notice or care about, but if we can find language that makes them happy and still serves the main audience, then all the better.

**Comment by aturon** [comment]
Thank you for these nits!  I agree with both. Mind opening up a PR to improve, and pinging me there?
