### ISSUE TITLE
Obsolete YouTube icon used in the site footer

### ISSUE THREAD

**Issue by xTibor** [rust-lang/beta.rust-lang.org#413]
YouTube dropped this style of social media icon used in the site footer years ago:

![958a129a-0510-4440-ba6e-8d8cedbd5ab1](https://user-images.githubusercontent.com/1627292/49245055-8f43b280-f411-11e8-8e97-fcea7f24eb7b.png)

For the up to date icons see the [YouTube Brand Resources](https://www.youtube.com/yt/about/brand-resources/#logos-icons-colors) page.

**Comment by ashleygwilliams** [comment]
@xTibor thanks for filing! if you're able to find an svg for the updated logo that matches these in design i would happily accept a PR for this!

**Comment by mitsuhiko** [comment]
An EPS file that can be trivially converted is here: https://www.youtube.com/yt/about/media/downloads/youtube_monochrome_dark_icon.zip

**Comment by ashleygwilliams** [comment]
thanks- i would happily accept a PR for this!
