### ISSUE TITLE
In getting started, show how start a simple program project before adding a dependency to it

### ISSUE THREAD

**Issue by meven** [rust-lang/beta.rust-lang.org#415]
# Content Feature Request
## Summary
I would suggest to put the getting started paragraph "Adding a dependency" after "A small Rust application".

## Motivation
It seems to me more important and easier to grasp to be able to write some code rather than hearing about dependency first. 
It avoids to have a sort of "nested" mental construct where you hear about a piece and then about the ensemble, it requires the reader to understand then the ensemble and how the piece fits all at once.

## Drawbacks
Perhaps this is what most new users would understand better.

This is some pretty nice work already ! :)

**Comment by ashleygwilliams** [comment]
i could imagine we could have folks run the hello world that is generated by cargo new, and then move on to adding dependencies. @aturon what do you think?

**Comment by aturon** [comment]
@ashleygwilliams yep,  that sounds like a good compromise!

**Comment by ashleygwilliams** [comment]
i can probably make a PR for this today :)

**Comment by meven** [comment]
I can offer a PR if you want.
I would make the necessary rephrasing.
Also I feel you need to tell the user to basically 
> cd hello-rust
Before running cargo.

**Comment by ashleygwilliams** [comment]
whoops- just saw this @meven - i am working on a PR right now. thanks for volunteering tho!
