### ISSUE TITLE
Add a link to the Rust cookbook in the learn page

### ISSUE THREAD

**Issue by meven** [rust-lang/beta.rust-lang.org#418]
# Content Feature Request
## Summary
One nice source of examples for newcomers growing to intermediates users is the Rust cookbook https://github.com/rust-lang-nursery/rust-cookbook
We should add a link to it in the learn page.

## Motivation
The Rust cookbook is a step after Rust by example which focuses on language and language basics.
The cookbook instead teaches how to leverages great crates in a getting things done style.

## Drawbacks
 - One more link may is more complexity for the user
- The cookbook content is not worse a link to it from the main site.

**Comment by ashleygwilliams** [comment]
@steveklabnik does the docs team consider the rust cookbook an official and maintained resource? if so i am happy to add it, but my understanding was that it was no longer maintained.

**Comment by meven** [comment]
AFAIK it is unofficial.
It has some activity still https://github.com/rust-lang-nursery/rust-cookbook
It was started by the [rust lib blitz](https://blog.rust-lang.org/2017/05/05/libz-blitz.html) so it was kinda started by the team.
I always felt it did not have the exposure it would need to achieve its goal despite its nice content.

**Comment by aturon** [comment]
If/when the cookbook becomes an official book covered under the doc team purview, we can definitely consider linking to it, but right now it's not yet at that status.

**Comment by steveklabnik** [comment]
Yes, 👍 to what aaron said.

**Comment by 89z** [comment]
https://github.com/rust-lang/book/issues/858
https://github.com/rust-lang/rust/issues/49453
https://github.com/rust-lang/www.rust-lang.org/issues/1433

https://github.com/rust-lang/www.rust-lang.org/issues/418
