### ISSUE TITLE
Google calender integration does not fit/work

### ISSUE THREAD

**Issue by rugk** [rust-lang/beta.rust-lang.org#427]
# Design Feature Request
## Summary
The embedded Google calendar on the site is really not visually pleasing, it's not very helpful (does not provide much value) and has other issues.

My proposed idea: Use custom design and maybe fetch calendar events manually.

### not visually pleasing

first of all, it does not fit into the design at all. I mean have a look at the screenshot:
  
![image](https://user-images.githubusercontent.com/11966684/49247999-fdd83e80-f418-11e8-8035-3d3f6eb4d771.png)

…the whole website is designed, has it's own color schema and then you got this little tiny white thing with blue accent color, a big "Google" logo; all of that squashed into less than 300 pixels (width) as you can see in the screenshot it cannot even display the date in the German translation.

So it has a totally different design…

### not very helpful

I've just visited the new site for the first time and this catched my eye (not in a good way though, obviously; also as that is not really _the most_ important thing at the bottom), but looking at it (maybe also due to the condensed design), I also see: 
* it's may too much, you are confronted with 5 events this day or so and you can scroll up many, many times to find something useful

### Other issues
* privacy: the embed likely loads from Google. This can be a privacy issue.
* advertisement: thanks to the big Google logo and "add to Google calendar" link you "accidentally" do advertisement for Google, which is (said in a good way) totally off-topic for Rust. And I doubt, this is wanted.

### Idea

First of all, use the existing design. E.g. just fetch the next events from an API endpoint and add simple bullet points.
Maybe provide a link to "all items". IMHO, it is not really needed to see all events at the home page – I mean this a _home_ page, it does not need all details. Maybe add a separate "calendar"/"events" page or so…

## Drawbacks
It needs some implementation work. It's obviously not as easy as embedding an add-on.

## Rationale and alternatives
- Why is this design the best in the space of possible designs?
  It's not… :smile:  It's just an idea. I just think the current way does not work.

- What other designs have been considered and what is the rationale for not
  choosing them?
  Did not have more ideas…

- What is the impact of not doing this?
  Continuing this unpleasant thing, which can be seen to not fit into the page.

## Maintenance
Don't know.

## Unresolved Questions
No idea.

**Comment by ashleygwilliams** [comment]
if you are aware of a service that could do this for us we would be happy! the community team events subteam is planning on reworking how we manage events and this will likely be replaced by whatever service they end up using. i agree with your comments- it will just (as u also say), take a second to fix :)

cc @skade for events team

**Comment by huxi** [comment]
I literally made an audible "eew" sound when I first saw the calendar widget.

The rest of the site looks very polished so it stands out even more. I think simply changing "Upcoming Events" into a block looking similar to "Read Rust" and "Watch Rust", i.e. one paragraph of flavor text with a button linking to the Google calendar, would already be a huge visual improvement without too much extra work.

**Comment by rugk** [comment]
Well… as for your website integration, you could either call Google APIs directly (if they exist), or through a "proxy" on a server, which queries the API and just returns some results.

My intent was not really to replace it with another service, that would be unlikely to really fix the design issues. But if you want [Nextcloud calendars e.g. does seem to provide/want to provide a new embed](https://github.com/nextcloud/calendar/issues/741). Anyway, I guess a *real* integration into the existing design (instead of a cheap embed) would be always preferably.

**Comment by Maxgy** [comment]
I personally think the calendar should  be removed from the site and instead link to an external page.

**Comment by wsy2220** [comment]
This is also very unfriendly for people outside free world like China.
All access to Google service are banned here.
