### ISSUE TITLE
Use the WebAssembly logo

### ISSUE THREAD

**Issue by PayasR** [rust-lang/beta.rust-lang.org#428]
Can we please use the official WebAssembly logo on the home page instead of the generic one currently used?

**Comment by ashleygwilliams** [comment]
can you be more specific? the current one is from the official webassembly website.

**Comment by PayasR** [comment]
https://webassembly.org/css/webassembly.svg is the official Logo that was voted upon [here](https://github.com/WebAssembly/design/issues/980). The logo assets are available [here](https://github.com/carlosbaraza/web-assembly-logo)

**Comment by ashleygwilliams** [comment]
we... are using exactly that svg? 
<img width="310" alt="screen shot 2018-11-29 at 3 39 46 pm" src="https://user-images.githubusercontent.com/1163554/49250531-0b77cf00-f3ed-11e8-82ce-4b651c71660a.png">

**Comment by ashleygwilliams** [comment]
oh i see. on the homepage. no, we won't do that as there are not official logos for the others and it makes the design inconsistent. i'm going to close this.
