### ISSUE TITLE
Confusing button naming

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/beta.rust-lang.org#430]
# Content Bug Report

## Page(s) Affected
http://beta.rust-lang.org/

## What needs to be fixed?
There are buttons named things like "Learn more", "Get started", "Check it out", and also pages named "Learn" and "Getting started", but the buttons don't take you to those pages.

The reason this happens is because the text on all of the buttons is generally meaningless and is just contextual - it takes you to more information about whatever section the button is in. This is confusing when you've just been to a page like "Getting started", want to go back there, and the links don't take you where you expect.

I imagine this is really bad for accessibility too, as screen readers will likely just read what's on a button and it will all be the same.

## Suggested Improvement
Where possible, have the text on the button reflect the name of the page it takes you to. When this is not possible, have standard text like "More info...", or a standard icon, and make sure that text does not clash with the name of any of the pages on the site.

Possibly you don't even need all these buttons - you can just make the headings, or entire sections clickable.

**Comment by ashleygwilliams** [comment]
if you have specific suggestions for the rewording of some buttons i would welcome PR(s) that make those changes. it's likely easier to review in a PR format, so please feel free to make one and we can discuss there! thanks for filing!

**Comment by laszlokorte** [comment]
Suggestions:
"Get started" -> "Read the book"
"Check it out" -> "Watch the videos"
"Learn more" -> "Read contribution guide"

**Comment by ashleygwilliams** [comment]
@laszlokorte i would happily accept a PR for this (if you are interested!) otherwise i can make one later today. great suggestions, thank you!

**Comment by ankushChatterjee** [comment]
> Suggestions:
> "Get started" -> "Read the book"
> "Check it out" -> "Watch the videos"
> "Learn more" -> "Read contribution guide"
 Starting out here so will like to make a PR for these specific content changes, is PR still welcome?

**Comment by chriskrycho** [comment]
Definitely, @ankushChatterjee!

**Comment by ankushChatterjee** [comment]
Please check PR #567
