### ISSUE TITLE
The new site seems to be aimed at managers, not developers

### ISSUE THREAD

**Issue by kballard** [rust-lang/beta.rust-lang.org#431]
Looking at the new site, it feels like it's aimed at marketing towards managers, not at developers. Some elements of the site are an improvement, like the specific usage examples (Command Line, WebAssembly, etc), but on the whole it feels like a downgrade.

Here's some specific issues I have with the new site that I feel the old site did much better:

- The new site is a lot more complicated. The old site was refreshingly simple; lots of white space, the only color was a nice blue. The new site uses a lot more colors and is a lot more visually noisy in general. Especially that "Rust in production" section.
- With the old site, the Documentation / Install / Community / Contribute header was prominent. With the new site it's significantly de-emphasized. Which is a shame because that navigation header is usually what I'm looking for when I go to the site.
- The runnable code example on the old site. One of the cardinal sins of programming language websites is not providing an example of what the language looks like. I know it's kind of superficial, but every time I see a website for a language I'm unfamiliar with, one of the very first things I want to know is "what does a snippet of code in this language actually look like?" and this is something most programming language websites actually fail at. The fact that the snippet on rust-lang.org is runnable is even better. On the new site, even the "Learn" link doesn't show me a code example. The only code examples I can find are tiny non-runnable snippets on the Command Line and Networking pages, and those aren't even syntax-highlighted (and they're also showing scrollbars even when there's no scrolling needed; it looks rather ugly).
- Some of the "Featuring" bullets on the old site are I think rather important and don't exist on the new one. "zero-cost abstractions", "guaranteed memory safety", and "threads without data races" are all really compelling features of Rust and the new site rather de-emphasizes this. Personally, the fact that Rust guarantees memory safety and freedom from data races with zero runtime overhead is one of the most compelling features of the language.

The new site is an improvement in some ways. For example, merely having more prose on the new site allows it to make arguments that the old site can't, such as

> Rust is blazingly fast and memory-efficient: with no runtime or garbage collector, it can power performance-critical services, run on embedded devices, and easily integrate with other languages.

But I think there's a middle ground that can be reached here.

In fact, the more I think about it, the more I wonder if the best solution here isn't to basically take the old site, and add all the new content underneath the existing site content. The old site's front page is a single page of content (no scrolling on my desktop monitor). What if we take all the new content, change the styling to be less noisy and more similar to the old site, and just put it under the old site's content? The old site content can be tweaked too, such as replacing the old slogan with the new one. And to be honest, the code example on the old site is probably not the best example we could use, it's mostly just a bunch of `println!()` statements, which don't even show format arguments, just static strings.

**Comment by aturon** [comment]
@kballard 

> Looking at the new site, it feels like it's aimed at marketing towards managers, not at developers.

This is an intentional shift. During the first three years since 1.0, we've taken a "bottom-up" approach to marketing, but at this point it's increasingly important to present a good image to managers, CTOs, and similar. That said, I believe the site is *also* much more useful to developers than previously, by providing a far more extensive survey of important tools, application domains, and entry points to documentation.

At any rate, a large multi-faceted issue like this is not actionable, and at this stage we are definitely not open to a complete rethink. Several of the suggestions you make already have open issues. Please feel free to open other, actionable and narrow issues.
