### ISSUE TITLE
increase letter spacing on h2s

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/beta.rust-lang.org#432]
# Design Feature Request
## Summary
Consider using a different, less bulky font for headings.

## Motivation
The chosen font "Alfa Slab One" is extremely weighty and bold. IMO the letters are far too close together (bad kerning) and combined with the boldness of the letters this makes the site look cramped even though it isn't really.

## Unresolved Questions
* Which other font should be used?
* How to others feel about this?

**Comment by ashleygwilliams** [comment]
hi @jonas-schievink ! thanks for filing.

i don't think we are currently interested in changing the fonts at the moment. deciding on the fonts was a long design ordeal and generally, we are happy with them.

as for them seeming cramped, we could consider increasing the letter spacing. would this help address your issue?

**Comment by rep-nop** [comment]
Between the background rectangle that resides under it and the weight of the font its very hard to read the titles because the characters get cut in half (especially upper case) in contrast and are extremely close together. I also am not a fan of the styling of the font but the weight is the main issue.

**Comment by jonas-schievink** [comment]
Setting `letter-spacing: 1px;` certainly makes it *less* bad, yeah.

Before:

![screenshot-2018-11-29-21 41 21](https://user-images.githubusercontent.com/1786438/49251653-36304a80-f422-11e8-9355-284459a9c3c7.png)

After:

![screenshot-2018-11-29-21 58 18](https://user-images.githubusercontent.com/1786438/49251671-3fb9b280-f422-11e8-8ab0-5cd25d7a52dd.png)

(ignoring the weird colors, which is #408)

**Comment by ashleygwilliams** [comment]
thank you! i will work on a PR to improve the letter spacing :)

**Comment by jonas-schievink** [comment]
Same goes for `h1`s, really. Before:

![screenshot-2018-11-29-22 13 32](https://user-images.githubusercontent.com/1786438/49252357-1a2da880-f424-11e8-9543-aa93e76368e4.png)

After `letter-spacing: 1px;`:

![screenshot-2018-11-29-22 13 42](https://user-images.githubusercontent.com/1786438/49252366-24e83d80-f424-11e8-824c-e6b0e4aea1e5.png)

(other values for `letter-spacing` could also work well, but this is already an improvement IMO - I don't really know anything about font design though)

**Comment by regexident** [comment]
For the fixed headers one could even go as far (as a final touch-up) as add manual kerning. The "Ne" in "Networking" for example is really badly kerned, as is the "rk", etc.
