### ISSUE TITLE
Front page should have code sample

### ISSUE THREAD

**Issue by kballard** [rust-lang/beta.rust-lang.org#436]
# Content Feature Request
## Summary

A cardinal sin of programming language websites is not providing a code sample. The new site has 2 tiny code samples buried on secondary pages. It should have a prominent runnable code sample on the front page (like the old site does), or at the very least a prominent link to a page dedicated to showing off runnable code samples.

## Motivation
As a developer, knowing what the language actually looks like is important. And the fact that Rust has the capability to offer runnable code samples is really compelling because it lets the prospective user play with the language without installing anything.

## Drawbacks
The only real drawback I can think of is it takes up space. Having a prominent link to a secondary page full of runnable code samples minimizes the space usage, at the cost of not offering any code examples to someone who skims the page looking for them (which is what I usually do immediately upon encountering a website for a new language).

## Maintenance
This will be maintained the same way the code sample on the current rust-lang.org site has been maintained.

## Unresolved Questions
The current code example on rust-lang.org isn't great. It's mostly just a bunch of `println!()` statements, which don't even show off formatting since they're just printing static strings. It would be nice to update this to a more interesting code example. Perhaps a tiny program that uses the `regex` crate to do some manipulation of standard input, since the Rust Playground already exposes that crate?

**Comment by ashleygwilliams** [comment]
closing as is duplicate with already closed issue. https://github.com/rust-lang/beta.rust-lang.org/issues/396
