### ISSUE TITLE
typo: "ferris-says" and NOT "ferris_says"

### ISSUE THREAD

**Issue by shef** [rust-lang/beta.rust-lang.org#438]
# Content Bug Report

## Page(s) Affected
https://github.com/rust-lang/beta.rust-lang.org/blob/master/templates/learn/get-started.hbs#L82

## What needs to be fixed?
Typo in crate name: "_" instead of "-" in package name. Correct crate name is "ferris-says".

The example program will fail to build due to incorrect dependency package name.

## Suggested Improvement
(optional) Do you have a suggestion for how to fix the problem? Include your ideas
here.

**Comment by Manishearth** [comment]
(this can be closed, fixed by #439)

**Comment by ashleygwilliams** [comment]
closed by #439
