### ISSUE TITLE
Reliability section a little awkward

### ISSUE THREAD

**Issue by lfkeitel** [rust-lang/beta.rust-lang.org#444]
# Content Bug Report

## Page(s) Affected

Index page - Reliability paragraph

## What needs to be fixed?

The wording feels strange to me.

## Suggested Improvement

Change `guarantee` to `guarantees` and `enable` to `enables`:

> Rust’s rich type system and ownership model guarantee memory-safety and thread-safety — and enable you to eliminate many other classes of bugs at compile-time.

to

> Rust’s rich type system and ownership model guarantees memory-safety and thread-safety — and enables you to eliminate many other classes of bugs at compile-time.

**Comment by ashleygwilliams** [comment]
the current state is correct grammar. "Rust’s rich type system and ownership model" is a plural subject, so the verb should be plural.
