### ISSUE TITLE
Reduce padding on the hompage under the slogan

### ISSUE THREAD

**Issue by nicoburns** [rust-lang/beta.rust-lang.org#446]
# Reduce padding on the hompage
## Summary

Reduce padding / whitespace on the homepage

## Motivation

The current homepage doesn't not make effective use of space:

<img src="https://user-images.githubusercontent.com/3943692/49254345-ef8e2080-f420-11e8-8e77-5d918b90447a.png" />

**Comment by ashleygwilliams** [comment]
i would happily accept a PR that reduces the white space under the slogan! thanks!

**Comment by nicoburns** [comment]
If the PR above is accepted, then the homepage will look like this:

<img width="1440" alt="screenshot 2018-11-29 at 22 49 05" src="https://user-images.githubusercontent.com/1007307/49257080-0a649300-f429-11e8-8191-754664fa0ff3.png">

**Comment by ssokolow** [comment]
Having so little padding relative to the font size feels slightly cramped to me

Perhaps a *little* more padding below the slogan... more like the padding below the word "more" in the "Productivity" block?

**Comment by nicoburns** [comment]
@ssokolow I got the same feedback from Ashley. Final design that got merged looks like this:

![localhost_7878_ copy](https://user-images.githubusercontent.com/1007307/49259922-2a994f80-f433-11e8-95d2-58322f110a64.png)

**Comment by ssokolow** [comment]
Looks good. :)

(Well, I have other issues with the design, but the padding is no longer one of them.)

**Comment by ashleygwilliams** [comment]
I'm reopening this because I needed to revert the previous PR because it caused issues on pages with subtitles or long titles. i am very interested in a PR that would improve this- just we need to make sure it works for all pages. Sorry for the back and forth- i'm happy to work on this with someone if they'd like to take this on!

**Comment by ashleygwilliams** [comment]
@chriskrycho if you end up with some extra time, this would be a good one to check out :)

**Comment by chriskrycho** [comment]
Top of my list for Monday!

**Comment by nicoburns** [comment]
@chriskrycho I think this fixes the immediate issue with the previous PR, by replacing the tachyons class with padding defined in app.scss.

I'm unsure of what the overall strategy for CSS is, and I've never worked with tachyons or a similar framework before. But won't it always have this problem? That changes need to be applied individually to every page (or moved out of the tachyons system). Is there any plan to complement tachyons with an ITCSS framework like Inuit.css?

**Comment by chriskrycho** [comment]
Hey @nicoburns – thanks for submitting another PR!

At least for the present, we'll be sticking with Tachyons. The changes needing to be applied to individual pages is, in my view, a strength and not a weakness, given that the constraints for different pages are quite different. We may revisit that and wrap Tachyons in another layer at a later point, but for the moment, it's useful to lay things down with the desired layout now, and see what emerges as a kind of common pattern later.

Given the timelines, I'll probably end up just landing this myself, but it's not for lack of gratitude – it's great that you noticed this and I really appreciate the PRs!
