### ISSUE TITLE
user logos should be vertically centered on networking page

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/beta.rust-lang.org#447]
# Content Bug Report

## Page(s) Affected
http://beta.rust-lang.org/what/networking

## What needs to be fixed?

The Buoyant logo is placed in a way that makes it look like it belongs to the quote above (which is from Mozilla), not the correct quote on the left of it:

![screenshot-2018-11-29-23 41 12](https://user-images.githubusercontent.com/1786438/49256737-4818ea00-f430-11e8-8a5c-a4bbc129e892.png)

## Suggested Improvement
The logo should be vertically centered in its space and should be at the same height as the text it belongs to. Also consider reducing the distance between text and logo (it's rather large for the Firefox logo).

**Comment by ashleygwilliams** [comment]
i would happily accept a PR to fix this! thank you

**Comment by jonas-schievink** [comment]
Someone else will have to implement this, I've spent an hour wrangling CSS and couldn't get it to align properly without breaking responsiveness

**Comment by ashleygwilliams** [comment]
closed by #530
