### ISSUE TITLE
Stick the footer at the bottom when the page is too short

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/beta.rust-lang.org#450]
When the content is too short (for example in the [404 page](https://beta.rust-lang.org/404)) the footer is not located at the bottom, but in the middle of the page:

---

![screenshot from 2018-11-29 23-46-03](https://user-images.githubusercontent.com/2299951/49256973-0a689100-f431-11e8-8f88-b09d1fb0da5c.png)

---

Should it be brought down?

---

![screenshot from 2018-11-29 23-48-49](https://user-images.githubusercontent.com/2299951/49257063-5d424880-f431-11e8-93a2-1475cd9dd58a.png)

---

**Comment by ashleygwilliams** [comment]
i would happily accept a PR for this! thanks!
