### ISSUE TITLE
Serve WOFF fonts instead of TTF

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/beta.rust-lang.org#454]
## Summary

At the moment we serve TTF fonts to the users (even though [the CSS file tells the browser those are WOFF2?](https://github.com/rust-lang/beta.rust-lang.org/blob/9104226eba89ad15b996d7778228056fe1f8e9a7/static/styles/fonts.css#L7)), which is not optimal for performance. We should serve WOFF fonts instead.
## Motivation

Loading a page without images or embedded content for the first time (like [Governance](https://beta.rust-lang.org/governance)) at the moment downloads 2MB of data, and 1.8MB of those are the TTF FiraSans fonts (4 fonts weighting ~450kb each). Converting them to WOFF and WOFF2 halves their size:

```
486K FiraSans-ExtraBold.ttf
238K FiraSans-ExtraBold.woff
240K FiraSans-ExtraBold.woff2
```

That basically means sending half the data to the user just by compressing the fonts beforehand.

## Drawbacks

Mostly none, [WOFF is basically supported everywhere](https://caniuse.com/#search=woff).

## Rationale and alternatives

Technically WOFF2 *should* give us better compression ratio, but after converting a few of them seems like for FiraSans there is basically no difference between the two (WOFF is even smaller!). Since WOFF is more widely supported I'd stick with it.

## Maintenance

Adding a WOFF copy might add a bit of a maintenance work when the fonts are updated. We shouldn't update them so often though, and most downloadable font packages include WOFF files nowadays.

**Comment by ashleygwilliams** [comment]
did you see https://github.com/rust-lang/beta.rust-lang.org/pull/448? let me know what you think and if it addresses your concerns (i think it might address some but not all...)

**Comment by pietroalbini** [comment]
Well, that PR didn't exist when I started writing the issue `:(`
Yeah, that fixes my concerns!
