### ISSUE TITLE
add install to top nav

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/beta.rust-lang.org#459]
# Design Feature Request
## Summary
AFAICT, the "Getting Started" page is only on the home page. I propose we add it as a link in the navbar at the top of every page.

## Motivation
If new potential users cannot find this link, they may just give up.

## Drawbacks
It would be an additional link at the top of the page. I think this is worth it.

## Rationale and alternatives
This proposal is a simple change, which I think should have minimal disturbance of the current design.

Alternatives
- Add a link at the bottom of every page, say in the footer or as a last panel at the bottom of each page. Putting it in the footer might still be hard to find. Putting it as a panel at the bottom might take more design effort.
- Put it at the top of each page but not in the navbar. This might disrupt the current visual design and require some work.

## Maintenance
None necessary

## Unresolved Questions
None TMK

**Comment by ashleygwilliams** [comment]
@aturon i'm open to this- but i know the top nav has limited space. what do you think?

**Comment by ashleygwilliams** [comment]
(thanks for filing @mark-i-m !)

**Comment by mitsuhiko** [comment]
What if "tools" becomes "get" that has all the things on it (rust itself as well as the tools).

**Comment by ashleygwilliams** [comment]
i think "get" is very ambiguous, so i don't think i'd want that

**Comment by mark-i-m** [comment]
Perhaps "install" or "downloads"?

**Comment by nicoburns** [comment]
I feel like "tools" should become tools+download/install and include the top of the Getting Started page which has Rust installation (name of link to be decided).

I feel like the rest of the Getting Started page is a bit odd. It essentially duplicates content from the book (which everyone's going to have to read to achieve anything useful anyway). So I feel like we might be better off just linking straight to the book and removing that from this site entirely (until the book is merged into this site...).

**Comment by mitsuhiko** [comment]
Not sure if useful, but something around download is most common:

* Ruby: "Downloads" in navigation, "Download Ruby" on frontpage
* Golang: "Download Go" on frontpage
* Python: "Downloads" in navigation
* PHP: "Downloads" in navigation
* Kotlin: can't figure out how to download
* Elixir: "Install" in navigation
* Swift: "Download" in navigation
* Crystal: "Install" on frontpage

**Comment by mark-i-m** [comment]
> Kotlin: can't figure out how to download

Actually, neither can I... even after googling it... Perhaps a good example to _not_ emulate :stuck_out_tongue:

**Comment by nicoburns** [comment]
> > Kotlin: can't figure out how to download
> 
> Actually, neither can I... even after googling it... Perhaps a good example to _not_ emulate 😛

I wonder if this is a case of "Install it using the JetBrains IDE", which most of their target market already has. Still not great but it might explain it.

**Comment by lbolla** [comment]
I think a "Download" and a "Manual" link/button in the front page are a must. A good chunk of people visiting the website will be familiar with the language: they won't read blurbs, they'll just want links to download new releases and read the docs.

**Comment by ashleygwilliams** [comment]
ok, as an action item for this i will add an install link to the top nav (downloads is not... quite right here, and we use install in other places.) if there are other issues that came out of this that aren't addressed by that action, please file other issues (not because i disagree, but just so i can make sure to keep track). i'll open a PR for this shortly.
