### ISSUE TITLE
Update header highlights to be more readable

### ISSUE THREAD

**Issue by andrewkfiedler** [rust-lang/beta.rust-lang.org#460]
# Design Feature Request
## Summary
As of now the highlights are only half or so covering the headers.  This makes it a little hard to read.  I think covering the header with the highlight entirely will it more readable while still making the headers pop.  

Currently it looks like this:
![screen shot 2018-11-29 at 5 02 48 pm](https://user-images.githubusercontent.com/11984853/49260070-23ede680-f3f9-11e8-9f3a-e3fb3afe7622.png)

I would suggest something like this: 
![screen shot 2018-11-29 at 5 02 38 pm](https://user-images.githubusercontent.com/11984853/49260081-32d49900-f3f9-11e8-99fe-b07ab21ddb5c.png)

## Motivation
Why are we doing this? 
Readability would be my main thought.  

What use cases does it support? 
People with less acute vision.  It'll let people scan the page quicker.

What is the expected
outcome?
The header still pops, and the text is clear and readable.

## Drawbacks
Why should we _not_ do this?
There might be something about the design I'm not considering.

## Rationale and alternatives
- Why is this design the best in the space of possible designs?
Some of this will come down to opinion.  I think it'll be more accessible as a design though.
- What other designs have been considered and what is the rationale for not
  choosing them?
Another possibility:
![screen shot 2018-11-29 at 5 11 12 pm](https://user-images.githubusercontent.com/11984853/49260216-cad28280-f3f9-11e8-967d-46b20bfa0585.png)
This moves the highlight to be more of an underline.  The headers might not pop as much with this design.
- What is the impact of not doing this?
This is probably just an opinion on what people think looks best.

## Maintenance
I'm open to making a PR if others like this direction.  

## Unresolved Questions

**Comment by nicoburns** [comment]
I agree that this is an improvement. Also, MDN uses a similar style to your first proposal in some places https://developer.mozilla.org/en-US/ which is a pretty good association for Rust.

**Comment by ashleygwilliams** [comment]
i think for the moment we are going to keep the highlights as is. we may be interested in refinements in the new year, but for the moment i think we are going to close this. thank for for filing and i appreciate you taking the time to think about this. if you are interested, keep an eye on the website team that we'll be forming and consider asking for this to be reopened at that point, probably in late January next year, but i cant guarantee when.
