### ISSUE TITLE
Colour Scheme

### ISSUE THREAD

**Issue by jacobpledger** [rust-lang/beta.rust-lang.org#466]
## Summary
I just really don't like the colour scheme. I find parts hard to read, and I don't know how else to express my thoughts about it other than it puts me off. I know this might be personal taste, but as it's presented now, I think the site feels very childish. It doesn't fit with my idea of "Rust".

## Motivation
I just don't like it, I'm hoping others might weigh in if they agree and help express why.

## Proposal
Reconsider the colour palette. "Rust" makes me think more industrial. Greys, yellows, oranges, maybe greens. Colours of actual _rust_. Throw some blue in as water for Ferris. That's just me though, see what others have to say about it.
Most importantly consider accessibility and readability - some of the current colours aren't working well behind text, black or white. See #455 and #408 as examples for further reference of this.

## Drawbacks
It'll take time and effort, and others may disagree.

## Rationale and Alternatives
Rationale: The colours just bother me, but are also not very versatile in terms of accessibility/readability. 
Alternatives: Keep the current palette, possibly reduce use of certain colours in situations where they hinder usability.

**Comment by ashleygwilliams** [comment]
we are open to adjusting the color scheme to improve accessibility but we are not changing the color scheme wholesale at this time. if you would like to make specific small actionable suggestions, please file individual issues.
