### ISSUE TITLE
increase size of favicon

### ISSUE THREAD

**Issue by ariasuni** [rust-lang/beta.rust-lang.org#467]
## What needs to be fixed?
The favicon is too tiny; see the difference between the one on the beta website, and the current one on https://rust-lang.org.
![screenshot_20181130_044113](https://user-images.githubusercontent.com/2446451/49267358-4ebc5700-f45a-11e8-9a9a-6937e612ced8.png)

(Firefox Developer Edition, X11, 96x96 dots per inch)

**Comment by ashleygwilliams** [comment]
i would happily accept a PR to fix this
