### ISSUE TITLE
Consider rewording tagline to avoid systems programming

### ISSUE THREAD

**Issue by softprops** [rust-lang/beta.rust-lang.org#472]
## Summary
Explain what is going on.

> The programming language that empowers everyone to become a systems programmer.

This is a great tagline but a some which limits rusts potential audience. Many potential rustaceans are just looking for ways to build more reliable and efficient systems. Many of these potential users dont have systems programming in thier vocabulary and the tag line is lost on them so they move on

Proposed change. Cast a wider net for a wider reach

> The programming language that empowers everyone to _confidently_ build _reliable_ _efficient_ software

Trying hard not to be wordy but trying to capture the essence of confidence and reliability

**Comment by tshepang** [comment]
similar issue https://github.com/rust-lang/beta.rust-lang.org/issues/419

**Comment by ashleygwilliams** [comment]
Thanks for filing this @softprops - it's small and actionable and based on the blog post we wrote ! I'll talk to @aturon about it today.

**Comment by sector-f** [comment]
>reliable efficient software

Shouldn't that be "reliable, efficient software" (with a comma)?

**Comment by aturon** [comment]
Cross-linked in ongoing discussion [here](https://github.com/rust-lang/beta.rust-lang.org/issues/419#issuecomment-443307354).

**Comment by softprops** [comment]
closing this as a dup. I shared my thoughts in the other gh issue. thanks!
