### ISSUE TITLE
Consider having a "Latest news" section

### ISSUE THREAD

**Issue by lbolla** [rust-lang/beta.rust-lang.org#481]
# Content Feature Request
## Summary
Most programming language websites (Go, Python, Ruby, etc.) have a section showing recent news: new releases, new blog posts, etc. As it stand the landing page is pretty static: you see it once, you don't need to see it anymore.

## Motivation
You want your landing page to represent the language as best as possible, which also means giving the reader and idea of what's going on in the ecosystem.

## Drawbacks
No idea.

## Rationale and alternatives
- Even programmers familiar with Rust may find it useful, not just novices. As it stand, an experience programmer has no reason to visit the landing page

## Maintenance
This can be automated, using RSS feeds, or similar.

**Comment by ashleygwilliams** [comment]
Hi! We don't currently have this content, so I don't think we would consider this at this time. If you are interested in this, there is a subteam of the Community Team that handles content and is a great place to talk about this idea!
