### ISSUE TITLE
Reduced space for top header results in overflowed text

### ISSUE THREAD

**Issue by aturon** [rust-lang/beta.rust-lang.org#486]
Some of the subpages currently have title text that overflows into the sections below.

![image](https://user-images.githubusercontent.com/709807/49292765-02c1e000-f463-11e8-8746-86d58eb74ce0.png)

![image](https://user-images.githubusercontent.com/709807/49292784-110ffc00-f463-11e8-9a6c-01b0a64b07db.png)

**Comment by ashleygwilliams** [comment]
related https://github.com/rust-lang/beta.rust-lang.org/issues/446 (i reverted the PR that caused this so closing, and will track in the reopened other issue)
