### ISSUE TITLE
sites like doc.rust-lang and forge.rustlang still old

### ISSUE THREAD

**Issue by Maxgy** [rust-lang/beta.rust-lang.org#487]
Question:
Sites like doc.rust-lang.org and forge.rust-lang.org still exhibit the old website style.  Are these going to be revamped along with the main website to be more visually appealing?

**Comment by steveklabnik** [comment]
From https://blog.rust-lang.org/2018/11/29/a-new-look-for-rust-lang-org.html

> We also like the minimalist style of the current site, but it also may be too minimal. Furthermore, it has no room to grow; we have more than just rust-lang.org these days. We wanted a style that we could use to unify all of the websites that we maintain in the Rust project; crates.io being a big one. Its “pool table” design feels extremely different than rust-lang.org, which is confusing.

**Comment by ashleygwilliams** [comment]
They will be! I am going to close this issue, but know that we are going to be taking on this work for the rest of the year and into the beginning of next year. Thanks!
