### ISSUE TITLE
ferris_says export in main.rs

### ISSUE THREAD

**Issue by ashutoshpith** [rust-lang/beta.rust-lang.org#502]
# Content Feature Request
## in templates/learn/get-started.hbs - a small Rust application area
##we need to import the "ferris-says" in main.rs to use it ,without it couldn't compile.
like this..
![screenshot from 2018-12-01 01-58-42](https://user-images.githubusercontent.com/31169310/49313481-6a346a00-f50d-11e8-9ce0-4ba12c3f63fe.png)

**Comment by ashleygwilliams** [comment]
when the edition ships (which is when the site goes live) - you won't need the extern crate, and that is why it is removed now. i'm closing this because we want the example to work with the 2018 edition specifically.

**Comment by ashutoshpith** [comment]
it's already ending of 2018, max a month away. when it goes live
