### ISSUE TITLE
Getting a designer?

### ISSUE THREAD

**Issue by hwchen** [rust-lang/beta.rust-lang.org#507]
Hello,

I'm sorry to add to all the noise, but after reading through some of the issues, I wanted to raise the possibility of finding or hiring a designer.

I think that there are at least two good reasons:
- design is hard. And I don't want to demean the hard work of the core team on this website, but there are many visual design and UX issues that a designer would be able to fix. (at least as far as I can see from the issues, like color palette and empty space). (This is entirely separate from content issues).
- Design by committee can result in incoherency in the final product. Getting problems with the website fixed by filing issues might lose the overall vision for the site.

I'm not sure if you've already considered this, or are already using a designer, or if this is a matter of money. I'm sorry if there isn't an immediately actionable item here, but I thought the idea was worth bringing up.

**Comment by ashleygwilliams** [comment]
We worked with a designer on the current site. We are not going to consider large design changes at this time.
