### ISSUE TITLE
Run clippy on source

### ISSUE THREAD

**Issue by meven** [rust-lang/beta.rust-lang.org#511]
# Technical Bug Report

## Is this an issue with Rust, CSS, or HTML (or a combination)?
Issue with Rust source.

## Expected Behavior
`cargo clippy` should not output anything.
Unless the team decides not to use/take into account clippy.

## Current Behavior
We have a few cargo clippy warnings that can help have idiomatic rust code.
And with all clippy outputs you get a simple way to fix the warning.

## Step to Reproduce
run `cargo clippy`

**Comment by Dylan-DPC** [comment]
Thanks for reporting this. I think the better thing to do is run clippy over the source and submit a PR. It will be easier for the maintainers :)
