### ISSUE TITLE
"Build it in Rust" is too low-level for NOT "System" program language

### ISSUE THREAD

**Issue by inv2004** [rust-lang/beta.rust-lang.org#515]
# Content Feature Request
## Summary
There are two connected problems:
Please stop mark Rust as a "system" programming language. The mark reduces auditory of the language significantly + a lot of people do not use Rust for "system" programming, which is quite low-level: ML, Web, etc. We have connected issue here: https://github.com/rust-lang/beta.rust-lang.org/issues/472

The second one problem (probably connected to the first one) is "Build it in Rust" section:
If I would like a make a decision about unknown language for my project, what would you I see there?
1) "Command Line" - its something like small tools.
1.1) "Solid and quick" is the part on CLI only. It is solid for CLI only? The same for all other items of the CLI: "Easy distribution""Robust configuration", etc.
2) "WebAssembly" - is a good thing, but do we really have any stable solution here? + In the next "Networking" we have examples. I suppose its necessary to have examples for every section or to remove it.
3) "Networking". And again - it looks very low-level, but description of the paragraph is wider than just "networking": Its Web.
3.1) Separate question why async-hyper is not here - I understand that its more complicate than reqwest, but it could help point into fast async. Which is important for current web and streaming and etc.
4) "Embedded". I do not know about the topic a lot, but why "Powerful static analysis" and "Fearless concurrency" are in Embedded only?

Anyway, unrelated to internal description of the 1 2 3 4, Looks like Rust is the language for: small tools , low-level networking and embedded. It looks like a good alternative to C, but even not sure about C++. Maybe I am wrong, but I considering Rust more wide language, which is near Java, Go, which are not "system". Rust could be "system", but I believe it not the only point to sell + its not even very major point.

## Motivation
To make Rust more universal language and to cover wider audience.

## Drawbacks
If Rust way is to be "system programming" language only.

## Rationale and alternatives
- What is the impact of not doing this?
Rust maybe will be know to C and some C++ devs, but not to other devs.

**Comment by ashleygwilliams** [comment]
i believe this is well covered by https://github.com/rust-lang/beta.rust-lang.org/issues/458 and https://github.com/rust-lang/beta.rust-lang.org/issues/472 so i'm going to close this as duplicate- please feel free to elaborate on those issues!
