### ISSUE TITLE
webpage titles have unnecessary word "index"

### ISSUE THREAD

**Issue by Maxgy** [rust-lang/beta.rust-lang.org#521]
Upon opening the main beta.rust-lang.org page, the title of the tab says "Rust - index".  This seems sloppy and should be changed to just "Rust" or something of that source.  All of the other pages have the same issue.  For example, the title of the learn page is "Rust - learn/index" while it should be "Rust - learn" or remain as just "Rust".

**Comment by nrc** [comment]
dup of #330
