### ISSUE TITLE
Incorrect link to Airborne Engineering on Embedded page

### ISSUE THREAD

**Issue by adamgreig** [rust-lang/beta.rust-lang.org#529]
# Content Bug Report

## Page(s) Affected

http://beta.rust-lang.org/what/embedded

## What needs to be fixed?

The link to Airborne Engineering's website is an HTTPS link, but the website is not served over HTTPS.

## Suggested Improvement

Update link to http://www.ael.co.uk

**Comment by ashleygwilliams** [comment]
would happily accept a PR for this- great catch! thank you for filing.
