### ISSUE TITLE
Comma mistake in learn page

### ISSUE THREAD

**Issue by meven** [rust-lang/beta.rust-lang.org#534]
# Content Bug Report

## Page(s) Affected
https://beta.rust-lang.org/learn

## What needs to be fixed?
In the phrase :

> Affectionately nicknamed “the book,” _The Rust Programming_ Language will ...

The "book," with a comma inside the quotes seem quite odd.

## Suggested Improvement
Change the phrase to

> Affectionately nicknamed “the book”, _The Rust Programming Language_ will ...

**Comment by ashleygwilliams** [comment]
this is how the docs do style, and so while we disnt do it perfectly for release, we‘ve had folks making prs tp fix it across the site. i personally also think its a lil weird, but it is correct (depending on what style guide u pick) and so we opted to be consistent with the documentation style guide.
