### ISSUE TITLE
Use the design for other websites?

### ISSUE THREAD

**Issue by Aloso** [rust-lang/beta.rust-lang.org#550]
# Are there plans to unify the design across different rust websites?

Since the beta website introduces a new design with new colours, it would be natural to use a similar design for other rust websites, such as

- [blog.rust-lang.org](https://blog.rust-lang.org/)
- [users.rust-lang.org](https://users.rust-lang.org/)
- [reach.rust-lang.org](http://reach.rust-lang.org/)
- [crates.io](https://crates.io/)
- [docs.rs](https://docs.rs/)

At least changing the fonts and colours wouldn't be too hard. Are there plans to do this in the future?

**Comment by Maxgy** [comment]
dup #487

**Comment by ashleygwilliams** [comment]
closing as duplicate. we definitely intend to migrate other sites!
