### ISSUE TITLE
Where Rust is used  - including forks and dialects

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang/beta.rust-lang.org#556]
# Content Feature Request
## Summary
Usage is an important part of any programing language. As such, usage should be prominently shown on the website. Forks and dialects are also usage, as they do sometimes make it back into the language, or are useful for others.

## Motivation
We should encourage ppl to experiment with programs written in Rust, forks, and dialects. This would help grow the community.

## Drawbacks
This *could* slow down the language's development, or fragment the community. However, any big/widely-used language ends up fragmented one way or another: C++ has a wide range of dialects, not just because it's widely-used, but also because of its history and all the features that got added to it over the years. On the other hand, Lua also has a wide range of dialects and forks, but not due to a wide range of features - instead, it's just widely used enough (and simple enough) that ppl fork it for all sorts of reasons.

## Rationale and alternatives
- Why is this design the best in the space of possible designs?

By encouraging programs, forks and dialects, we strengthen our community through experimentation and real-life use cases. This is an improvement over the current RFC process, which relies solely on some ppl deciding something is a good idea or a bad idea without A/B testing it first. This is closer to e.g. the IETF model of RFC.

- What other designs have been considered and what is the rationale for not
  choosing them?

Java follows a very different model and doesn't prominently display uses of Java. This makes sense for Java, as Java's trademarks and licensing are intended to discourage public usage.

- What is the impact of not doing this?

Lua has transcended many of the issues that other languages face with regards to feature requests. As such, not doing this would put us with all those "other languages" that have issues with regards to feature requests.

## Maintenance
How will this content be maintained? Who will do it?

Lua [defers it to the community](https://www.lua.org/uses.html). For Rust, this should probably be maintained by someone close to the community.

## Unresolved Questions
What related issues do you consider out of scope for this feature that could be
addressed in the future independently of the solution that comes out of this
feature?

**Comment by ashleygwilliams** [comment]
Hi @SoniEx2 ! I think that dialects/forks of Rust are not currently in scope for the Rust website at this time. I'm not aware of any forks or dialects at the moment, if/when they emerge we can consider adding them to the site. I'm going to close for now as this is out of scope, for the moment, primarily cuz there aren't currently prominent folks/dialects. please do comment if i am incorrect on this!

**Comment by SoniEx2** [comment]
well I'm kinda trying to encourage forks here .-.

I feel like the rust ecosystem is too strongly against forking...

**Comment by eddyp** [comment]
There is just one AVR port which, as far as I know is a little outdated relative to current releases, but the 2018 edition could provide the rallying point for new contributions: https://github.com/avr-rust/rust
