### ISSUE TITLE
Unintended horizontal scrolling on iOS due to Calendar

### ISSUE THREAD

**Issue by djrenren** [rust-lang/beta.rust-lang.org#572]
# Technical Bug Report
The "Upcoming Events" calendar is too wide for the viewport. This makes the whole page scrollable to the right where it is entirely white except for where the calendar is visible.

## Your Environment
| Software         | Version(s) |
| ---------------- | ---------- |
| Form Factor      | Mobile |
| Browser Type     | Safari |
| Browser Version  | 12 |

## Is this an issue with Rust, CSS, or HTML (or a combination)?
CSS and HTML

## Expected Behavior
Calendar should fit in the mobile view and the page should not scroll horizontally.
 
## Current Behavior
Horizontal scrolling. Calendar is too wide.

## Step to Reproduce
View the page in mobile Safari.

## Screenshots
![img_2004](https://user-images.githubusercontent.com/634666/49605334-0a8ef200-f945-11e8-8112-7d06db695b8e.PNG)

**Comment by ashleygwilliams** [comment]
thank you for filing! this is indeed unfortunate!
